###################
# Simple Git Flow #
###################
# https://ru.stackoverflow.com/a/573773/199934
# All release-it options:
# https://github.com/release-it/release-it/blob/master/conf/release-it.json
# [INFO] Hooks:
# https://github.com/release-it/release-it#hooks
hooks:
  # [INFO][YAML] Block notation for multiline:
  # https://stackoverflow.com/a/49685727/5951529
  before:bump:
    changelog -f - | cat - CHANGELOG.md > temp
    mv temp CHANGELOG.md
  # [INFO] Merge branches with commit, use “-no-ff”:
  # https://ru.stackoverflow.com/a/573773/199934
  # [NOTE] Checkout force required:
  # “error: Your local changes to the following files would be overwritten by checkout”
  # https://stackoverflow.com/a/32556166/5951529
  # [INFO] Overwrite master branch from SashaDevelop branch:
  # https://stackoverflow.com/a/2763118/5951529
  # https://github.com/Kristinita/SashaGitHub/commit/016ea890a1f8a7facfb357e2f244c22ee5aff94c
  before:release:
    git commit -m "Changelog ${version}" &&
    git push origin HEAD &&
    git merge --no-ff --strategy=ours master &&
    git checkout -f master &&
    git merge --no-ff SashaDevelop
  after:release: git checkout SashaDevelop
git:
  # [NOTE] Required:
  # https://github.com/release-it/release-it/issues/233
  addUntrackedFiles: true
  changelog: changelog -f -
  # [NOTE] Required:
  # “ERROR Working dir must be clean.”
  requireCleanWorkingDir: false
  # [NOTE] Required:
  # “ERROR No upstream configured for current branch.”
  requireUpstream: false
  tagName: st3-%s
github:
  release: true
  tokenRef: GITHUB_TOKEN
npm:
  publish: false
